---
title: "Relative BPC Framework"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
```
#read input file with BPC content data, some formatting tweaks for Excel file
```{r}
median_structuredness_criterion <- read_excel("N_sgRNA_structured_ness_shannon_template.xlsx")
working <- median_structuredness_criterion %>% rename(`BPC` = `Structured-ness (51-nt)`) %>% 
rename(`BPC gmedian` = `gmedian...3`) %>% rename(`Shannon gmedian` = `gmedian...6`)
```

```{r}
rel_bpc <- numeric(length(working$BPC))
for (i in 1:length(working$BPC)) {
  rel_bpc[i] <- length(which(working$Structuredness < working$BPC[i])) / length(working$BPC)
}

rel_shannon <- numeric(length(working$shannon_movmedian_51))
for (i in 1:length(working$shannon_movmedian_51)) {
  rel_shannon[i] <- length(which(working$shannon_movmedian_51 < working$shannon_movmedian_51[i])) / length(working$shannon_movmedian_51)
}
```
#build list of nucleotides with BPC (and Shannon Entropy) values equal to true median value
#median values hardcoded to have the BPCrel value of 0.5.
```{r}
meds_bpc <- working %>% filter(Structuredness > median(working$Structuredness) - 0.000000001) %>% filter(Structuredness < median(working$Structuredness) + 0.00000001) %>% select(Nt) #%>% filter(`Above gmedian` == 1)
meds_shannon <- working %>% filter(shannon_movmedian_51 > median(working$shannon_movmedian_51) - 0.000000001) %>% filter(shannon_movmedian_51 < median(working$shannon_movmedian_51) + 0.000000001) %>% select(Nt) #%>% filter(`Above gmedian` == 1)

rel_bpc[meds_bpc$Nt] <- 0.5
rel_shannon[meds_shannon$Nt] <- 0.5

bin_bpc <- rep(0, length(working$Structuredness))
bin_bpc[which(rel_bpc > 0.50)] <- 1

bin_shannon <- rep(0, length(working$shannon_movmedian_51))
bin_shannon[which(rel_shannon < 0.50)] <- 1
```

```{r}
identical(working$`Above gmedian`, bin_bpc)
identical(working$`Below 0`, bin_shannon)
```
#test plots for subset of BPCrel data
```{r}
relativebpc_bound <- as.data.frame(cbind(working$Nt, rel_bpc, bin_bpc))
relativebpc_bound <- relativebpc_bound %>% rename(`Nt` = `V1`)

relativebpcshannon_bound <- as.data.frame(cbind(working$Nt, rel_bpc, bin_bpc, rel_shannon, bin_shannon))
relativebpcshannon_bound <- relativebpcshannon_bound %>% rename(`Nt` = `V1`)
relativebpcshannon_bound_firstten <- relativebpcshannon_bound %>% filter(Nt < 10000)
working_firstten <- working %>% filter(Nt < 10000)
  
ggplot(data=working_firstten, aes(x=working_firstten$Nt, y=working_firstten$Structuredness, group=1)) + geom_line()
ggplot(data=relativebpcshannon_bound_firstten, aes(x=relativebpcshannon_bound_firstten$Nt, y=relativebpcshannon_bound_firstten$rel_bpc, group=1)) + geom_line()

#write.csv(relativebpc_bound, file = "rel_bpcshannon_n-sgRNA.csv", row.names = FALSE)
```

